-- MySQL Script generated by MySQL Workbench
-- Mon Dec 25 11:40:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema comprasmercado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comprasmercado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comprasmercado` DEFAULT CHARACTER SET utf8 ;
USE `comprasmercado` ;

-- -----------------------------------------------------
-- Table `comprasmercado`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprasmercado`.`local` (
  `idlocal` INT NOT NULL,
  `nomelocal` VARCHAR(100) NULL,
  PRIMARY KEY (`idlocal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comprasmercado`.`unidademedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprasmercado`.`unidademedida` (
  `idunidademedida` INT NOT NULL,
  `nomeunidademedida` VARCHAR(100) NULL,
  PRIMARY KEY (`idunidademedida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comprasmercado`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprasmercado`.`produto` (
  `idproduto` INT NOT NULL,
  ` nomeproduto` VARCHAR(100) NULL,
  `unidademedida_idunidademedida` INT NOT NULL,
  PRIMARY KEY (`idproduto`, `unidademedida_idunidademedida`),
  INDEX `fk_produto_unidademedida1_idx` (`unidademedida_idunidademedida` ASC),
  CONSTRAINT `fk_produto_unidademedida1`
    FOREIGN KEY (`unidademedida_idunidademedida`)
    REFERENCES `comprasmercado`.`unidademedida` (`idunidademedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comprasmercado`.`compraproduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comprasmercado`.`compraproduto` (
  `idcompraproduto` INT NOT NULL,
  `datacompraproduto` DATE NULL,
  `local_idlocal` INT NOT NULL,
  `precoproduto` DECIMAL(16,2) NULL,
  `quantidadeproduto` DECIMAL(16,2) NULL,
  `produto_idproduto` INT NOT NULL,
  `produto_unidademedida_idunidademedida` INT NOT NULL,
  PRIMARY KEY (`idcompraproduto`, `local_idlocal`, `produto_idproduto`, `produto_unidademedida_idunidademedida`),
  INDEX `fk_compra_local_idx` (`local_idlocal` ASC),
  INDEX `fk_compraproduto_produto1_idx` (`produto_idproduto` ASC, `produto_unidademedida_idunidademedida` ASC),
  CONSTRAINT `fk_compra_local`
    FOREIGN KEY (`local_idlocal`)
    REFERENCES `comprasmercado`.`local` (`idlocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compraproduto_produto1`
    FOREIGN KEY (`produto_idproduto` , `produto_unidademedida_idunidademedida`)
    REFERENCES `comprasmercado`.`produto` (`idproduto` , `unidademedida_idunidademedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
